export const baseballTeams = [
    'Chicago White Sox',
    'Cleveland Guardians',
    'Detroit Tigers',
    'Kansas City Royals',
    'Minnesota Twins',
    'Chicago Cubs',
    'Cincinnati Reds',
    'Milwaukee Brewers',
    'Pittsburgh Pirates',
    'St. Louis Cardinals',
    'Baltimore Orioles',
    'Boston Red Sox',
    'New York Yankess',
    'Tampa Bay Rays',
    'Toronto Blue Jays',
    'Atlanta Braves',
    'Miami Marlins',
    'New York Mets',
    'Philadelphia Phillies',
    'Washington Nationals',
    'Houston Astros',
    'Los Angeles Angels',
    'Oakland Athletics',
    'Seattle Mariners',
    'Texas Rangers',
    'Arizona Diamondbacks',
    'Colorado Rockies',
    'Los Angeles Dodgers',
    'San Diego Padres',
    'San Francisco Giants'
]