export const footballTeams = [
            'Arizona Cardinals',
            'Baltimore Ravens',
            'Atlanta Falcons',
            'Buffalo Bills',
            'Carolina Panthers',
            'Cincinnati Bengals',
            'Chicago Bears',
            'Cleveland Browns',
            'Dallas Cowboys',
            'Denver Broncos',
            'Detroit Lions',
            'Houston Texans',
            'Green Bay Packers',
            'Indianapolis Colts',
            'Los Angeles Rams',
            'Jacksonville Jaguars',
            'Minnesota Vikings',
            'Kansas City Chiefs',
            'New Orleans Saints',
            'Las Vegas Raiders',
            'New York Giants',
            'Los Angeles Chargers',
            'Philadelphia Eagles',
            'Miami Dolphins',
            'San Francisco 49ers',
            'New England Patrios',
            'Seattle Seahawks',
            'New York Jets',
            'Tampa Bay Buccaneers',
            'Pittsburgh Steelers',
            'Washington Commanders',
            'Tennessee Titans'
            
        ]